### ISSUE TITLE
Call recording

### ISSUE THREAD

**Issue by mizzunet** [Chooloo/koler#116]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
As title, implies, Call Recording feature 👍 
**Describe alternatives you've considered**
I haven't found any except using AOSP dialer
**Additional context**
![Screenshot_20201205-235853_Phone](https://user-images.githubusercontent.com/10193999/101260437-da59d400-3755-11eb-989a-726d27736b8d.png)

**Comment by DhruvSangal** [comment]
Is this feature added in the code? unable to find it if added?

**Comment by mizzunet** [comment]
> Is this feature added in the code? unable to find it if added?

No it is not, my bad, I forgot to specify. That was taken from AOSP dialer

**Comment by qw123wh** [comment]
it takes a lot of work for call recording, but maybe this can help  https://github.com/TitaniumOS/packages_apps_Dialer/commit/3490f197271677caa47673274c95a7ea7ed1f133

**Comment by mizzunet** [comment]
Thank, looking forward to seeing this :)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by O-DoC** [comment]
Hi,
It has also the same option in huawei dialer :
 1. You have a direct access button on in-call screen (start, stop)
 2. Or could enable auto start recording in the app config (three dots\settings\callautorecord) with two options :
  2.1 enabled on/off
  2.2 select case all/selected numbers
  2.3 if 'selected numbers'  : it display a third option menu option which open your contacts with check box sélection
 3. In same config menu (three dot\recordings) it opens the list of recorded audio files (in Sounds/CallRecord folder)
 4. File format : [contact full name]@[phone number]_[timestamp yyyyMMddHHmmss]
   Or just [phone number]_[timestamp yyyyMMddHHmmss] if not in contact list

Is very useful, clean and lightweight.

![Screenshot_20210407_193219_com android incallui](https://user-images.githubusercontent.com/61201263/113949351-0c9b4100-97dd-11eb-917e-8ee24990f043.jpg)

**Comment by moriel5** [comment]
I personally use True Caller nowadays, precisely because of this.
It's problematic for user apps to support call recording on Android 11+, however this would be a boon for users on a ROM (custom or stock) that already contains the necessary binaries, in which case Koler simply needs to hook into the system API.

**Comment by Github-contribute** [comment]
Pls add call recorder as soon as possible or make separate flash zip with full support of call record. I don't like aosp dialer UI. Its pretty old UI. That's y I moved to koler. I really like modern material you UI. Only thing I miss is call recorder. @roeiedri

**Comment by Pheggas** [comment]
This is a real deal breaker for me. I would never use dialer that doesn't have recording option. Nowadays they everywhere put gdialer and think that everything is fine. But it's not. I need to have 3rd party app to record those calls.

**Comment by moriel5** [comment]
I no longer use Truecaller nowadays, because in my opinion it has become bloatware, however I still make sure to use phone apps that expose call recording features (whether on their own, on older Android versions, or by relying upon system binaries).

@Github-contribute That is quite an interesting take, I actually prefer Koler's GUI over some other dialer app GUIs precisely because it is similar to the AOSP dialer (to a degree), though I still think that the dialer's GUI in the original material days was (mostly) superior to anything around nowadays.

**Comment by saswatasarkar13** [comment]
Hello, Any update?
