### ISSUE TITLE
Dialer formats international numbers wrong

### ISSUE THREAD

**Issue by G3O-CH** [Chooloo/koler#117]
Hi

The phone numbers from my contacts are stored in international format ([E.164](https://en.wikipedia.org/wiki/E.164)).
A Swiss number with the national format 031 123 45 67 is stored as +41311234567.
The app shows the numbers correctly with the national format.
When I want to call this number, the app dials only 41311234567 (without the +) and this ends in an error.
When I enter manually the number +41311234567 it works, but it's very boring to note every number and enter it manually in the correct format.
This makes the app useless as dialler.

Best regards from Switzerland
Christopher

**Comment by zhirzh** [comment]
i think this is a parsing issue in `Contact.getMainPhoneNumber()` caused by `java.net.URLDecoder.decode()`
the leading plus (`+`) is decoded into space(` `)

https://github.com/Chooloo/koler/blob/f437ead62882328520a1119db708ef01f647136b/app/src/main/java/com/chooloo/www/callmanager/database/entity/Contact.java#L183-L190

**Comment by G3O-CH** [comment]
@zhirzh 
You're right: It replaces the + with a space, that I haven't seen on a first view.
This will be the problem, thanks.
