### ISSUE TITLE
Display contact pictures in Recents tab

### ISSUE THREAD

**Issue by mizzunet** [Chooloo/koler#163]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Display picture of contacts on call logs.

#### Is your feature request related to a problem? Please describe it

No

#### How will you/everyone benefit from this feature?

Would look better. And...

**Comment by roeiedri** [comment]
Soo yeah i thought about it but there needs to be a UX separation between the contact screen and the recent screen
The recent should only display data regarding the recent call itself (a photo isnt a recent data) and so as the contact
Instead of the picture in the recent screen i put the call type icon

**Comment by mizzunet** [comment]
> Soo yeah i thought about it but there needs to be a UX separation between the contact screen and the recent screen
> The recent should only display data regarding the recent call itself (a photo isnt a recent data) and so as the contact
> Instead of the picture in the recent screen i put the call type icon (which is a recent call data)

I see
