### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by Subbarao6338** [Chooloo/koler#176]
Add Aurora dailer code in koler app

**Comment by xunil89** [comment]
It would be a good addition since the delaier aurora project is in abandonment! You can also feel the lack of groups in my opinion....

**Comment by xunil89** [comment]
https://t.me/AuroraOSS/15217

**Comment by roeiedri** [comment]
Can you be more specific?

**Comment by xunil89** [comment]
> Can you be more specific?

On the link I gave us there's some source code that might come in handy, instead of rewriting an app from scratch he could have forked the linked one or used part of the code if they're written in the same language. If it is possible it would be nice to have groups in the tabs as well. Very nice app though! 👍🏻

**Comment by mizzunet** [comment]
> > Can you be more specific?
> 
> On the link I gave us there's some source code that might come in handy, instead of rewriting an app from scratch he could have forked the linked one or used part of the code if they're written in the same language. If it is possible it would be nice to have groups in the tabs as well. Very nice app though! 👍🏻

AFAIK, Koler has been here before Aurora team made the Dialer.
