### ISSUE TITLE
Show call button only by swipe

### ISSUE THREAD

**Issue by Mojienjoynent** [Chooloo/koler#211]
When I tap on circle dots at bottom to show the numeric pad (numbers pad) I can't see call button. And I should swipe up number pad to show the call button and tap to call.
I use Los 14.1 , Huawei y360
![Screenshot_20210510-183340](https://user-images.githubusercontent.com/68327458/117672560-35896a00-b1bf-11eb-94f8-68c741927eac.png)

 And after swipe .
![Screenshot_20210510-183344](https://user-images.githubusercontent.com/68327458/117672609-40dc9580-b1bf-11eb-801f-3d441fdc9eea.png)

**Comment by Mojienjoynent** [comment]
Huawei, Y360
Lineage 14.1
I wrote it above

**Comment by roeiedri** [comment]
That's because your screen size is too small, and I'm trying to make the app as responsive as possible so in order to not damage the text size quality and overall experience it's a bit of a problem.
Pretty annoying I know but also the way the code works, it's also an headache to change that (that screen has a fixed relative size) and changing that would take some digging and time :(
