### ISSUE TITLE
Be able to disable auto orientation

### ISSUE THREAD

**Issue by airikr-e** [Chooloo/koler#313]
### Checklist

- [x] I am using the latest version - 1.3.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

As of now, the app will change orientation however you hold the phone. If you hold it in landscape mode, the app will show the content in landscape mode (left or right). It even change the orientation to up-sidedown! My honest view of this? It is incredible annoying!

It have happened far too many times when I am trying to answer a call, I accidentaly press hangup because the orientation had changed.

Please, add an option in the settings where you can disable automatic orientation :) I always have system auto orientation disabled.

#### Is your feature request related to a problem? Please describe it

Missing feature, can't disable automatic orientation.

#### Additional context

None.

#### How will you/everyone benefit from this feature?

Less irritation, more happiness.

**Comment by Ilithy** [comment]
Have you tested with the latest version? (1.4.0) because I just tested on my smartphone (pixel 6 pro under Grapheneos - Android 12)
I don't have this problem, the automatic orientation is disabled, Koler reacts normally as it keeps the portrait mode, it will surely help the developer to help you if you give more details (device, android version, stock or custom rom etc...)
