### ISSUE TITLE
Open with system dialer.

### ISSUE THREAD

**Issue by simanchal-45** [Chooloo/koler#325]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info
 - Android version/Custom ROM version: 8.1
 - Device model: Oppo a5s

When I make a call from koler it's open with system dialer app while I make koler default

**Comment by gun4qmm7h** [comment]
This happens to me as well. I think koler is crashing and the os is using the system dialer instead. I think this is the answer because if you disable the system dialer, there will be no UI when calling and a pop up will start saying that koler keeps crashing.
Note* if you do disable the system dialer with this bug, you won't be able to hang up the call or do anything.

**Comment by Ilithy** [comment]
Me too, exactly the same (on android 12) I'm back on the aosp dialer in the meantime (much less pleasant though:))

**Comment by gun4qmm7h** [comment]
It works, thank you

**Comment by Ilithy** [comment]
Me too, everything works perfectly, thank you.

**Comment by simanchal-45** [comment]
Not working on my Oppo a5s ( Android 8.1).

**Comment by gun4qmm7h** [comment]
Are you on version 1.4.3?

**Comment by simanchal-45** [comment]
Yes. Don't know what's the problem.
